name: Build and Inspect Dist

on:
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Match your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Upload Dist Folder
      uses: actions/upload-artifact@v3
      with:
        name: dist-folder
        path: dist # Upload the `dist` folder for inspection
